# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'XBToastDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XBToastDemo

pod 'XBAlertViewBase'
pod 'Masonry'

  target 'XBToastDemoTests' do
    inherit! :search_paths
  #  pod 'Masonry'
  #  pod 'XBAlertViewBase'
  end

  target 'XBToastDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
